version: '8.0'

services:
    fc.codeflix.catalog.fb:
        container_name: catalogdb
        hostname: catalogdb
        image: mysql
        ports:
        - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: rsb@142529 

    rabbitmq: 
       container_name: adm_videos_rabbitmq
       image: rabbitmq:3.12.1-management
       hostname: rabbitmq
       environment:
        - RABBITMQ_DEFAULT_USER=adm_videos
        - RABBITMQ_DEFAULT_PASS=123456
       ports:
        - 15672:15672
        - 5672:5672 

networks:
    default:
        name: service_catalog


